

-- CREATE DATABASE AWOTRADE

CREATE SCHEMA AWOTRADE;

-- CREATE TABLE CUSTOMERS

CREATE TABLE CUSTOMERS (
CustomerID INT,
CustomerName VARCHAR(50),
ContactName VARCHAR(50),
Address VARCHAR(80),
City VARCHAR(30),
PostalCode VARCHAR(10),
Country VARCHAR(20)
);


-- CATEGORIES TABLE

CREATE TABLE CATEGORIES (
CategoryID INT NOT NULL,
CategoryName VARCHAR(50),
Description VARCHAR(200)
);


-- EMPLOYEES TABLE

CREATE TABLE EMPLOYEES (
EmployeeID INT NOT NULL,
LastName VARCHAR(50),
FirstName VARCHAR(50),
BirthDate DATE,
Email VARCHAR(50),
Notes VARCHAR(200)
);


-- ORDERDETAILS TABLE

CREATE TABLE ORDERDETAILS (
OrderDetailID INT NOT NULL,
OrderID INT,
ProductID INT,
Quantity INT
);